export const glossary: Record<string, string> = {
  amplify:
    "AWS Amplify — a managed hosting service for static web applications. Used to host the briefing UI SPA.",
  "api-gateway":
    "Amazon API Gateway — a managed HTTP API service with JWT authorization, CORS, and throttling. Routes requests to the Query Lambda.",
  bedrock:
    "Amazon Bedrock — a fully managed service for accessing foundation models (embedding and LLM) via a unified API.",
  cognito:
    "Amazon Cognito — a user authentication service providing user pools, JWT tokens, and group-based authorization.",
  cosine:
    "Cosine similarity — a distance metric that measures the angle between two vectors. Values range from 0 (opposite) to 1 (identical direction). Preferred for text embeddings.",
  "data-type":
    "The numeric precision for stored vectors. This project uses float32 (32-bit floating point).",
  dimension:
    "The number of floating-point values in each vector. Must match the embedding model output exactly (1024 for Titan Embeddings V2).",
  "distance-metric":
    "The algorithm used to measure similarity between vectors. Options are cosine (angle-based) and euclidean (straight-line distance).",
  embedding:
    "A vector representation of text — a list of floating-point numbers that captures semantic meaning. Generated by an embedding model.",
  "embedding-model":
    "Amazon Titan Embeddings V2 (amazon.titan-embed-text-v2:0) — converts text into 1024-dimensional vectors for similarity search.",
  eventbridge:
    "Amazon EventBridge — a serverless event bus. Used here for the daily scheduled corpus ingest cron trigger.",
  "inference-profile":
    "A Bedrock cross-region inference profile that routes requests to the nearest available region. Used for the LLM (au.anthropic.claude-sonnet-4-5-20250929-v1:0).",
  lambda:
    "AWS Lambda — serverless compute. This project uses two functions: ingest (RSS → embed → store) and query (search → answer).",
  llm: "Large Language Model — Anthropic Claude accessed via Bedrock inference profile. Generates structured answers from retrieved context.",
  "put-vectors":
    "S3 Vectors PutVectors API — stores one or more vectors with associated metadata in a vector index.",
  "query-vectors":
    "S3 Vectors QueryVectors API — finds the most similar vectors to a query vector using Top-K nearest neighbor search.",
  rag: "Retrieval-Augmented Generation — a pattern that combines vector similarity search with LLM generation to produce grounded answers.",
  "s3-vectors":
    "Amazon S3 Vectors — a purpose-built vector storage capability within S3 that enables similarity search over embeddings without a separate vector database.",
  terraform:
    "HashiCorp Terraform — infrastructure-as-code tool used to provision all AWS resources in this demo.",
  "titan-v2":
    "Amazon Titan Embeddings V2 — the Bedrock foundation model used to generate 1024-dimensional text embeddings.",
  "top-k": "The number of nearest neighbor results returned by a vector similarity search query.",
  "vector-bucket":
    "A specialized S3 bucket type (aws_s3vectors_vector_bucket) that hosts vector indexes for similarity search.",
  "vector-index":
    "A named index (aws_s3vectors_index) within a vector bucket defining dimension, distance metric, and data type.",
};
